[package]
name = "faccess"
version = "0.2.1"
authors = ["Thomas Hurst <tom@hur.st>"]
edition = "2018"
description = "Simple file accessibility checks"
repository = "https://github.com/Freaky/faccess"
license = "MIT"
keywords = ["file", "access"]
categories = ["api-bindings", "filesystem"]
readme = "README.md"

[target.'cfg(unix)'.dependencies]
libc = "~0.2.68"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["accctrl", "aclapi", "handleapi", "impl-default", "minwindef", "processthreadsapi", "securitybaseapi", "winbase", "winerror", "winnt"] }

[dependencies]
bitflags = "1.2.1"

[package.metadata.docs.rs]
# Docs are identical across targets.
targets = []
